apiVersion: v1
kind: Service
metadata:
  name: cache
  namespace: {{ .Values.namespace }}
  labels:
    name: cache-svc
    app: {{ .Values.appName }}
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: cache-pod
    app: {{ .Values.appName }}