apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: {{ .Values.namespace }}
  labels:
    name: mongo-svc
    app: {{ .Values.appName }}
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo-pod
    app: {{ .Values.appName }}