apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: {{ .Values.namespace }}
  labels:
    name: zookeeper-svc
    app: {{ .Values.appName }}
spec:
  ports:
    - port: 2181
      targetPort: 2181
  selector:
    name: zookeeper-pod
    app: {{ .Values.appName }}