{
 "title": "Quecto Link",
 "description": "Best URL Shortner",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values({instance=\"45.198.13.134:9100\"},instance)"
    }
   },
   { "name": "status_codes", "query": { "query": "label_values(status_code)" } }
  ]
 },
 "panels": [
  { "title": "Mongo Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Command Latency (micro seconds)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_opLatencies_latency{op_type=\"commands\"}[5m]) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Size (KB)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_dbstats_storageSize{database=\"quectolink\"} / 1024 ",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Redis Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Connected Clients",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_connected_clients", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Used (MiB)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_memory_used_bytes / (1024 * 1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Application Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Total Http Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(url_shortener_http_requests_total{status_code=~\"$status_codes\", path!=\"/metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Node Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Disk Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (sum(node_filesystem_avail_bytes{instance=~\"$instance\"}) / sum(node_filesystem_size_bytes{instance=~\"$instance\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (sum(node_memory_MemAvailable_bytes{instance=~\"$instance\"})/ sum(node_memory_MemTotal_bytes{instance=~\"$instance\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m])) by (instance)) \r\n/ \r\nsum(rate(node_cpu_seconds_total[5m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Utilization",
   "type": "timeseries",
   "description": "The Network Utilization Chart provides a visual representation of network traffic over time, allowing users to monitor incoming + outgoing data rates. This chart is essential for identifying trends, potential bottlenecks, and overall network performance.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "(sum(rate(node_network_receive_bytes_total{instance=~\"$instance\"}[5m])) + sum(rate(node_network_transmit_bytes_total{instance=~\"$instance\"}[5m]))) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Namespace Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{namespace=~\"$namespace\"}[5m])) by (namespace) / (1024 * 1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "sum(rate(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~'$namespace'}[5m])) by (namespace) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pod Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "This chart displays the memory usage of each pod in each namespace over the last 5 minutes, aggregated by pod and presented in mebibytes (MiB). This allows for easier monitoring of memory consumption trends and helps identify potential memory-related issues.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{namespace=~\"$namespace\"}[5m])) by (pod) / (1024 * 1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "This chart displays the CPU usage of each pod in each namespace, calculated as the per-second rate of CPU time consumed over the last 5 minutes. The data is aggregated by pod, providing insights into CPU consumption trends and helping to identify performance bottlenecks or resource contention. Use this graph to monitor pod activity and ensure resource requests align with actual usage.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "sum(rate(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~'$namespace'}[5m])) by (pod) * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}