apiVersion: monitoring.coreos.com/v1 
kind: PrometheusRule 
metadata: 
  labels: 
    release: prometheus 
  name: resource-usage-alerts 
  namespace: monitoring 
spec: 
  groups: 
    - name: resource-usage-group 
      rules: 
        - alert: HighCpuUsage 
          expr: 100 - (avg(rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 80 
          for: 30s 
          labels: 
            severity: critical 
            source: prometheus 
          annotations: 
            description: "CPU usage on instance {{ $labels.instance }} exceeds 80%." 
            summary: "Critical: High CPU usage: {{ $value }}% detected on instance {{ $labels.instance }}."  
        - alert: HighMemoryUsage 
          expr: 100 * (1 - (sum(node_memory_MemAvailable_bytes) by (instance) / sum(node_memory_MemTotal_bytes) by (instance))) > 80 
          for: 30s 
          labels: 
            severity: critical 
            source: prometheus 
          annotations: 
            description: "Memory usage on instance {{ $labels.instance }} exceeds 80%." 
            summary: "Critical: High Memory usage: {{ $value }}% detected on instance {{ $labels.instance }}."   
        - alert: HighDiskUsage 
          expr: (1 - (sum(node_filesystem_free_bytes) by (instance) / sum(node_filesystem_size_bytes) by (instance))) * 100 > 80 
          for: 30s 
          labels: 
            severity: critical 
            source: prometheus 
          annotations: 
            description: "Disk usage on instance {{ $labels.instance }} exceeds 80%." 
            summary: "Critical: High Disk usage: {{ $value }}% detected on instance {{ $labels.instance }}." 