alertmanager:
  enabled: true
  alertmanagerSpec:
    forceEnableClusterMode: true
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: []  
      group_interval: 5m
      repeat_interval: 3h
      receiver: 'telepush'
      routes:
        - match:
            alertname: Watchdog
          receiver: 'null'  
    receivers:
      - name: 'telepush'
        webhook_configs:
          - url: 'https://telepush.dev/api/inlets/alertmanager/<token>'
      - name: 'null'  
        webhook_configs: []
