
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
  frontend:
    build: ./frontend
    ports:
      - "80:80"
  cache:
    image: redis:alpine
    ports:
      - "6379:6379"
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
