services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/your_db_name
      - PORT=5000
      - JWT_SECRET=your_jwt_secret
  frontend:
    build: ./frontend
    ports:
      - "80:80"
  cache:
    image: redis:alpine
    ports:
      - "6379:6379"
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
