services:
  backend:
    image: programmingninjas/quectolink-backend:latest
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "${PORT}:${PORT}"
  frontend:
    image: programmingninjas/quectolink:latest
    ports:
      - "80:80"
  cache:
    image: redis:alpine
    ports:
      - "6379:6379"
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
