apiVersion: v1
kind: Pod
metadata:
  name: zookeeper-pod
  labels:
    name: zookeeper-pod
    app: quectolink
spec:
  containers:
  - name: zookeeper
    image: zookeeper
    ports:
    - containerPort: 2181