apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-volume
  namespace: {{ .Values.namespace }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/zookeeper"
