apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: userapi-cert
spec:
  secretName: userapi-tls
  dnsNames:
  - quecto.fr.to
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
