apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  labels:
    name: frontend-deploy
    app: quectolink
spec:
  replicas: 3
  selector:
    matchLabels:
      name: frontend-pod
      app: quectolink
  template:
    metadata:
      name: frontend-pod
      labels:
        name: frontend-pod
        app: quectolink
    spec:
      containers:
      - name: frontend
        image: programmingninjas/quectolink
        envFrom:
         - configMapRef:
             name: frontend-config
        ports:
        - containerPort: 80
