apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-set
  labels:
    name: mongo-set
    app: quectolink
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongo-pod
      app: quectolink
  template:
    metadata:
      name: mongo-pod
      labels:
        name: mongo-pod
        app: quectolink
    spec:
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-claim
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-storage
          mountPath: "/data/db"
