apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    name: backend-svc
    app: quectolink
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    name: backend-pod
    app: quectolink
