apiVersion: v1
kind: Service
metadata:
  name: cache
  labels:
    name: cache-svc
    app: quectolink
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: cache-pod
    app: quectolink