apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    name: frontend-svc
    app: quectolink
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: frontend-pod
    app: quectolink
