apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    name: frontend-svc
    app: quectolink
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  selector:
    name: frontend-pod
    app: quectolink