apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo-svc
    app: quectolink
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo-pod
    app: quectolink