apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    name: zookeeper-svc
    app: quectolink
spec:
  ports:
    - port: 2181
      targetPort: 2181
  selector:
    name: zookeeper-pod
    app: quectolink