apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-claim
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
