apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Values.namespace }}
data:
  MONGO_URI: {{ .Values.configmap.backend_data.MONGO_URI }}
  PORT: {{ .Values.configmap.backend_data.PORT }}
