apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Values.namespace | quote }}
data:
  MONGO_URI: {{ .Values.configmap.backend_data.MONGO_URI | quote }}
  PORT: {{ .Values.configmap.backend_data.PORT | quote }}
