name: Pull changes and Run docker-compose on Azure VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        # Add Azure VM host to known_hosts
        ssh-keyscan -H ${{ secrets.AZURE_VM_HOST }} >> ~/.ssh/known_hosts

    - name: SSH into Azure VM, pull changes, and run docker-compose
      run: ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USERNAME }}@${{ secrets.AZURE_VM_HOST }} 'cd quectoLink && git pull origin master && docker-compose up -d --build'
      env:
        AZURE_VM_HOST: ${{ secrets.AZURE_VM_HOST }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
